@startuml
skinparam classAttributeIconSize 0
class Humain {
 -nom: String
    -prenom: String
    -dateNaissance: Date
    +Humain(nom: String, prenom: String, dateNaissance: Date)
    +getNom(): String
    +setNom(nom: String): void
    +getPrenom(): String
    +setPrenom(prenom: String): void
    +getDateNaissance(): Date
    +setDateNaissance(dateNaissance: Date): void
    +donneTexte(): string
}


Humain <|-- Joueur
class Joueur{
    -numero: int
    +Joueur(nom: String, prenom: String, dateNaissance: Date, numero: int, equipe: Equipe)
    +getNumero(): int
    +setNumero(numero: int): void
    +getEquipe(): Equipe
    +setEquipe(equipe: Equipe): void
    +donneTexte(): string
}





class Evenement{
    -horaire: Time
    -description: String
    +Evenement(horaire: Time, description: String)
    +getHoraire(): Time
    +setHoraire(horaire: Time): void
    +getDescription(): String
    +setDescription(description: String): void
    +donneTexte(): string
}

Joueur "1 \n-joueurEntrant" <--x  Remplacement
Joueur "1 \n-joueurSortant" <--x  Remplacement
Evenement <|-- Remplacement
class Remplacement{

    +Remplacement(horaire: Time, description: String, joueurSortant: Joueur, joueurEntrant: Joueur)
    +getJoueurSortant(): Joueur
    +setJoueurSortant(joueurSortant: Joueur): void
    +getJoueurEntrant(): Joueur
    +setJoueurEntrant(joueurEntrant: Joueur): void
    +donneTexte(): string
}

Evenement <|-- FaitDeJeu
Joueur "1 \n-joueurAuteur" <--x  FaitDeJeu
class FaitDeJeu{
    +FaitDeJeu(horaire: Time, description: String, joueurAuteur: Joueur)
    +getJoueurAuteur(): Joueur
    +setJoueurAuteur(joueurAuteur: Joueur): void
    +donneTexte(): string
}

 FaitDeJeu <|-- Faute
Joueur "1 \n-joueurVictime" <--x  Faute
class Faute{
    -carton: String
    +Faute(horaire: Time, description: String, joueurAuteur: Joueur, joueurVictime: Joueur, carton: String)
    +getJoueurVictime(): Joueur
    +setJoueurVictime(joueurVictime: Joueur): void
    +getCarton(): String
    +setCarton(carton: String): void
    +donneTexte(): string
}


@enduml